const pricelist = {
  MARGHERITA: 400,
  "DOUBLE CHEESE MARGHERITA": 530,
  "FARM HOUSE": 370,
  "PEPPY PANEER": 430,
  "MEXICAN GREEN WAVE": 480,
  "DELUXE VEGGIE": 350,
  "CHEESE N CORN": 430,
  "PANEER MAKHANI": 520,
  "VEGGIE PARADISE": 750,
};

export default pricelist;
